export const INCREMENT_ACTION = "INCREMENT_ACTION";
export const DECREMENT_ACTION = "DECREMENT_ACTION";
export const RESET_ACTION = "RESET_ACTION";
export const CHANGE_COUNT = "CHANGE_COUNT";
export const DEFAULT_VALUE = "DEFAULT_VALUE";
